# Generated by Django 5.0.3 on 2024-05-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_balite_datte_camany_balite_campany_client_buying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datte',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datte_set', to='api.client'),
        ),
    ]
